name: Ubuntu
on:
  workflow_dispatch:
    inputs:
      NGROK_AUTH_TOKEN:
        description: 'Enter Your NGROK Auth Token'
        required: true
        default: 'asidjaijdiasdjaoidjqw_asjduiajdiasd'
        type: string

jobs:
  init:
    name: Initialize Ubuntu-Latest Instance
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
        
        
      - name: NGROK and credentials
        run: |
          sudo apt install snapd
          sudo passwd -d root
          sudo passwd -d runner
          
      
      - name: Install ngrok
        run: sudo snap install ngrok
      - name: Create Folder NGROK
        run: sudo chmod 700 /root/ngrok


      - name: Auth Ngrok
        run: sudo ngrok authtoken $Env:NGROK_AUTH_TOKEN --config ./ngrok.yml
        env:
          NGROK_AUTH_TOKEN: ${{ inputs.NGROK_AUTH_TOKEN }}
          
      - name: Create Tunnel
        run: sudo ngrok tcp 3389


      - name: Prepare the self-destruct trigger
        run: |
          sudo cp ./ubuntu/daemon/maintain.sh /root/
          sudo chmod +x /root/maintain.sh
          sudo touch /root/remove_me_for_self_destruct
          sudo chmod +r /root/remove_me_for_self_destruct
          sudo cp ./ubuntu/daemon/self_destruct.sh /root/
          sudo chmod +x /root/self_destruct.sh
          sudo cp ./ubuntu/daemon/regret.sh /root/
          sudo chmod +x /root/regret.sh
          echo "=============================================================="
          echo "Run either command to terminate after at most 1 minute:"
          echo "---------------------------------------------------------"
          echo "sudo rm -f /root/remove_me_for_self_destruct"
          echo "sudo /root/self_destruct.sh"
          echo "=============================================================="
          echo "=============================================================="
          echo "Run either command if you regret within 1 minute:"
          echo "---------------------------------------------------------"
          echo "sudo touch /root/remove_me_for_self_destruct"
          echo "sudo /root/regret.sh"
          echo "=============================================================="
      - name: Maintaining
        run: |
          sudo /root/maintain.sh
