name: Ubuntu2
on:
  workflow_dispatch:
    inputs:
      NGROK_AUTH_TOKEN:
        description: 'Enter Your NGROK Auth Token'
        required: true
        default: 'asidjaijdiasdjaoidjqw_asjduiajdiasd'
        type: string

defaults:
  run:
    shell: bash
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Creating User to Login
      run: |
         sudo useradd -m ash && sudo adduser ash sudo && echo 'ash:ash' | sudo chpasswd

     
    - name: Installing Desktop Environment (wait for 10 min)
      run: sudo apt update && sudo apt install expect ubuntu-desktop
    - name: Installing Google Chrome Headless
      run: |
            sudo useradd -m Ubuntu 
            sudo adduser Ubuntu sudo
            echo 'Ubuntu:1234' | sudo chpasswd
            sudo sed -i 's/\/bin\/sh/\/bin\/bash/g' /etc/passwd
            sudo apt-get update
            sudo apt-get install xfce4-terminal -y

        
    - name: Install ngrok
      run: |
          curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null && echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list && sudo apt update && sudo apt install ngrok       


    - name: Auth Ngrok
      run: sudo ngrok authtoken 2CoIPsEZfDvyWdcYfWGcq6vuRcw_6g2RSLS1N5CeexPfJyzuw
      
    - name: Create Tunnel
      run: sudo ngrok tcp 3389


    - name: Prepare the self-destruct trigger
      run: |
        sudo cp ./ubuntu/daemon/maintain.sh /root/
        sudo chmod +x /root/maintain.sh
        sudo touch /root/remove_me_for_self_destruct
        sudo chmod +r /root/remove_me_for_self_destruct
        sudo cp ./ubuntu/daemon/self_destruct.sh /root/
        sudo chmod +x /root/self_destruct.sh
        sudo cp ./ubuntu/daemon/regret.sh /root/
        sudo chmod +x /root/regret.sh
        echo "=============================================================="
        echo "Run either command to terminate after at most 1 minute:"
        echo "---------------------------------------------------------"
        echo "sudo rm -f /root/remove_me_for_self_destruct"
        echo "sudo /root/self_destruct.sh"
        echo "=============================================================="
        echo "=============================================================="
        echo "Run either command if you regret within 1 minute:"
        echo "---------------------------------------------------------"
        echo "sudo touch /root/remove_me_for_self_destruct"
        echo "sudo /root/regret.sh"
        echo "=============================================================="
    - name: Maintaining
      run: |
        sudo /root/maintain.sh
