name: windowsWithoutRunner

on: 
  workflow_dispatch:
    inputs:
      NGROK_AUTH_TOKEN:
        description: 'Enter Your NGROK Auth Token'
        required: true
        default: 'asidjaijdiasdjaoidjqw_asjduiajdiasd'
        type: string


jobs:
  init:
    name: Initialize Windows-Latest Instance
    runs-on: windows-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Turn off the firewall
        run: |
          netsh advfirewall set allprofiles state off
      - name: Remove password complexity requirements
        run: |
          secedit /export /cfg c:\secpol.cfg
          (gc C:\secpol.cfg).replace("PasswordComplexity = 1", "PasswordComplexity = 0") | Out-File C:\secpol.cfg
          secedit /configure /db c:\windows\security\local.sdb /cfg c:\secpol.cfg /areas SECURITYPOLICY
          rm -force c:\secpol.cfg -confirm:$false
      - name: Allow users with blank passwords to log in remotely
        run: |
          Set-ItemProperty -Path HKLM:\SYSTEM\CurrentControlSet\Control\Lsa -Name LimitBlankPasswordUse -Value 0 -Force


      - name: Download NGROK
        run: Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
      - name: Extract
        run: Expand-Archive ngrok.zip
      - name: Change Ngrok location
        run: |
          New-Item "C:\ngrok" -type directory
          Copy-Item ".\ngrok\ngrok.exe" -Destination "C:\ngrok\"
          .\windows\n2n\edge_install.exe install
      - name: Auth Ngrok
        run: C:\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
        env:
          NGROK_AUTH_TOKEN: ${{ inputs.NGROK_AUTH_TOKEN }}
          
#       - name: Change Ngrok config yaml location
#         run: |
#           Copy-Item "C:\Users\runneradmin/.ngrok2/ngrok.yml" -Destination "C:\ngrok\"
#           .\windows\n2n\edge_install.exe install     

      - name: Remove password complexity requirements
        run: |
          secedit /export /cfg c:\secpol.cfg
          (gc C:\secpol.cfg).replace("PasswordComplexity = 1", "PasswordComplexity = 0") | Out-File C:\secpol.cfg
          secedit /configure /db c:\windows\security\local.sdb /cfg c:\secpol.cfg /areas SECURITYPOLICY
          rm -force c:\secpol.cfg -confirm:$false
      - name: Allow users with blank passwords to log in remotely
        run: |
          Set-ItemProperty -Path HKLM:\SYSTEM\CurrentControlSet\Control\Lsa -Name LimitBlankPasswordUse -Value 0 -Force
          
#       - run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
#       - run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)
      - name: Create Tunnel
        run: C:\ngrok\ngrok.exe tcp 3389



      - name: Prepare the self-destruct trigger
        run: |
          Copy-Item ".\windows\daemon\maintain.bat" -Destination "D:\"
          New-Item "D:\remove_me_for_self_destruct" -type file
          Copy-Item ".\windows\daemon\self_destruct.bat" -Destination "D:\"
          Copy-Item ".\windows\daemon\regret.bat" -Destination "D:\"
          echo "=============================================================="
          echo "Run this command to terminate after at most 1 minute:"
          echo "---------------------------------------------------------"
          echo "D:\self_destruct.bat"
          echo "=============================================================="
          echo "=============================================================="
          echo "Run this command if you regret within 1 minute:"
          echo "---------------------------------------------------------"
          echo "D:\regret.bat"
          echo "=============================================================="  
      - name: Maintaining
        run: |
          D:\maintain.bat
